// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appmaster.proto

#ifndef PROTOBUF_appmaster_2eproto__INCLUDED
#define PROTOBUF_appmaster_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "galaxy.pb.h"
// @@protoc_insertion_point(includes)

namespace baidu {
namespace galaxy {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_appmaster_2eproto();
void protobuf_AssignDesc_appmaster_2eproto();
void protobuf_ShutdownFile_appmaster_2eproto();

class AssignTaskRequest;
class AssignTaskResponse;
class ListTasksRequest;
class ListTasksResponse;
class StartTaskRequest;
class StartTaskResponse;
class StopTaskRequest;
class StopTaskResponse;
class UpdateTaskRequest;
class UpdateTaskResponse;
class ExecuteCmdRequest;
class ExecuteCmdResponse;

// ===================================================================

class AssignTaskRequest : public ::google::protobuf::Message {
 public:
  AssignTaskRequest();
  virtual ~AssignTaskRequest();

  AssignTaskRequest(const AssignTaskRequest& from);

  inline AssignTaskRequest& operator=(const AssignTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AssignTaskRequest& default_instance();

  void Swap(AssignTaskRequest* other);

  // implements Message ----------------------------------------------

  AssignTaskRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AssignTaskRequest& from);
  void MergeFrom(const AssignTaskRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.AssignTaskRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static AssignTaskRequest* default_instance_;
};
// -------------------------------------------------------------------

class AssignTaskResponse : public ::google::protobuf::Message {
 public:
  AssignTaskResponse();
  virtual ~AssignTaskResponse();

  AssignTaskResponse(const AssignTaskResponse& from);

  inline AssignTaskResponse& operator=(const AssignTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AssignTaskResponse& default_instance();

  void Swap(AssignTaskResponse* other);

  // implements Message ----------------------------------------------

  AssignTaskResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AssignTaskResponse& from);
  void MergeFrom(const AssignTaskResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.AssignTaskResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static AssignTaskResponse* default_instance_;
};
// -------------------------------------------------------------------

class ListTasksRequest : public ::google::protobuf::Message {
 public:
  ListTasksRequest();
  virtual ~ListTasksRequest();

  ListTasksRequest(const ListTasksRequest& from);

  inline ListTasksRequest& operator=(const ListTasksRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListTasksRequest& default_instance();

  void Swap(ListTasksRequest* other);

  // implements Message ----------------------------------------------

  ListTasksRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListTasksRequest& from);
  void MergeFrom(const ListTasksRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.ListTasksRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static ListTasksRequest* default_instance_;
};
// -------------------------------------------------------------------

class ListTasksResponse : public ::google::protobuf::Message {
 public:
  ListTasksResponse();
  virtual ~ListTasksResponse();

  ListTasksResponse(const ListTasksResponse& from);

  inline ListTasksResponse& operator=(const ListTasksResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListTasksResponse& default_instance();

  void Swap(ListTasksResponse* other);

  // implements Message ----------------------------------------------

  ListTasksResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListTasksResponse& from);
  void MergeFrom(const ListTasksResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.ListTasksResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static ListTasksResponse* default_instance_;
};
// -------------------------------------------------------------------

class StartTaskRequest : public ::google::protobuf::Message {
 public:
  StartTaskRequest();
  virtual ~StartTaskRequest();

  StartTaskRequest(const StartTaskRequest& from);

  inline StartTaskRequest& operator=(const StartTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartTaskRequest& default_instance();

  void Swap(StartTaskRequest* other);

  // implements Message ----------------------------------------------

  StartTaskRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StartTaskRequest& from);
  void MergeFrom(const StartTaskRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.StartTaskRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static StartTaskRequest* default_instance_;
};
// -------------------------------------------------------------------

class StartTaskResponse : public ::google::protobuf::Message {
 public:
  StartTaskResponse();
  virtual ~StartTaskResponse();

  StartTaskResponse(const StartTaskResponse& from);

  inline StartTaskResponse& operator=(const StartTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartTaskResponse& default_instance();

  void Swap(StartTaskResponse* other);

  // implements Message ----------------------------------------------

  StartTaskResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StartTaskResponse& from);
  void MergeFrom(const StartTaskResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.StartTaskResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static StartTaskResponse* default_instance_;
};
// -------------------------------------------------------------------

class StopTaskRequest : public ::google::protobuf::Message {
 public:
  StopTaskRequest();
  virtual ~StopTaskRequest();

  StopTaskRequest(const StopTaskRequest& from);

  inline StopTaskRequest& operator=(const StopTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StopTaskRequest& default_instance();

  void Swap(StopTaskRequest* other);

  // implements Message ----------------------------------------------

  StopTaskRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StopTaskRequest& from);
  void MergeFrom(const StopTaskRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.StopTaskRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static StopTaskRequest* default_instance_;
};
// -------------------------------------------------------------------

class StopTaskResponse : public ::google::protobuf::Message {
 public:
  StopTaskResponse();
  virtual ~StopTaskResponse();

  StopTaskResponse(const StopTaskResponse& from);

  inline StopTaskResponse& operator=(const StopTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StopTaskResponse& default_instance();

  void Swap(StopTaskResponse* other);

  // implements Message ----------------------------------------------

  StopTaskResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StopTaskResponse& from);
  void MergeFrom(const StopTaskResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.StopTaskResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static StopTaskResponse* default_instance_;
};
// -------------------------------------------------------------------

class UpdateTaskRequest : public ::google::protobuf::Message {
 public:
  UpdateTaskRequest();
  virtual ~UpdateTaskRequest();

  UpdateTaskRequest(const UpdateTaskRequest& from);

  inline UpdateTaskRequest& operator=(const UpdateTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateTaskRequest& default_instance();

  void Swap(UpdateTaskRequest* other);

  // implements Message ----------------------------------------------

  UpdateTaskRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateTaskRequest& from);
  void MergeFrom(const UpdateTaskRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.UpdateTaskRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static UpdateTaskRequest* default_instance_;
};
// -------------------------------------------------------------------

class UpdateTaskResponse : public ::google::protobuf::Message {
 public:
  UpdateTaskResponse();
  virtual ~UpdateTaskResponse();

  UpdateTaskResponse(const UpdateTaskResponse& from);

  inline UpdateTaskResponse& operator=(const UpdateTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateTaskResponse& default_instance();

  void Swap(UpdateTaskResponse* other);

  // implements Message ----------------------------------------------

  UpdateTaskResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateTaskResponse& from);
  void MergeFrom(const UpdateTaskResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.UpdateTaskResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static UpdateTaskResponse* default_instance_;
};
// -------------------------------------------------------------------

class ExecuteCmdRequest : public ::google::protobuf::Message {
 public:
  ExecuteCmdRequest();
  virtual ~ExecuteCmdRequest();

  ExecuteCmdRequest(const ExecuteCmdRequest& from);

  inline ExecuteCmdRequest& operator=(const ExecuteCmdRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExecuteCmdRequest& default_instance();

  void Swap(ExecuteCmdRequest* other);

  // implements Message ----------------------------------------------

  ExecuteCmdRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExecuteCmdRequest& from);
  void MergeFrom(const ExecuteCmdRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.ExecuteCmdRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static ExecuteCmdRequest* default_instance_;
};
// -------------------------------------------------------------------

class ExecuteCmdResponse : public ::google::protobuf::Message {
 public:
  ExecuteCmdResponse();
  virtual ~ExecuteCmdResponse();

  ExecuteCmdResponse(const ExecuteCmdResponse& from);

  inline ExecuteCmdResponse& operator=(const ExecuteCmdResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExecuteCmdResponse& default_instance();

  void Swap(ExecuteCmdResponse* other);

  // implements Message ----------------------------------------------

  ExecuteCmdResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExecuteCmdResponse& from);
  void MergeFrom(const ExecuteCmdResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:baidu.galaxy.ExecuteCmdResponse)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_appmaster_2eproto();
  friend void protobuf_AssignDesc_appmaster_2eproto();
  friend void protobuf_ShutdownFile_appmaster_2eproto();

  void InitAsDefaultInstance();
  static ExecuteCmdResponse* default_instance_;
};
// ===================================================================

class AppMaster_Stub;

class AppMaster : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline AppMaster() {};
 public:
  virtual ~AppMaster();

  typedef AppMaster_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void AssignTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::AssignTaskRequest* request,
                       ::baidu::galaxy::AssignTaskResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void ListTasks(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::ListTasksRequest* request,
                       ::baidu::galaxy::ListTasksResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void StartTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::StartTaskRequest* request,
                       ::baidu::galaxy::StartTaskResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void StopTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::StopTaskRequest* request,
                       ::baidu::galaxy::StopTaskResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void UpdateTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::UpdateTaskRequest* request,
                       ::baidu::galaxy::UpdateTaskResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void ExecuteCmd(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::ExecuteCmdRequest* request,
                       ::baidu::galaxy::ExecuteCmdResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(AppMaster);
};

class AppMaster_Stub : public AppMaster {
 public:
  AppMaster_Stub(::google::protobuf::RpcChannel* channel);
  AppMaster_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~AppMaster_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements AppMaster ------------------------------------------

  void AssignTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::AssignTaskRequest* request,
                       ::baidu::galaxy::AssignTaskResponse* response,
                       ::google::protobuf::Closure* done);
  void ListTasks(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::ListTasksRequest* request,
                       ::baidu::galaxy::ListTasksResponse* response,
                       ::google::protobuf::Closure* done);
  void StartTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::StartTaskRequest* request,
                       ::baidu::galaxy::StartTaskResponse* response,
                       ::google::protobuf::Closure* done);
  void StopTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::StopTaskRequest* request,
                       ::baidu::galaxy::StopTaskResponse* response,
                       ::google::protobuf::Closure* done);
  void UpdateTask(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::UpdateTaskRequest* request,
                       ::baidu::galaxy::UpdateTaskResponse* response,
                       ::google::protobuf::Closure* done);
  void ExecuteCmd(::google::protobuf::RpcController* controller,
                       const ::baidu::galaxy::ExecuteCmdRequest* request,
                       ::baidu::galaxy::ExecuteCmdResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(AppMaster_Stub);
};


// ===================================================================


// ===================================================================

// AssignTaskRequest

// -------------------------------------------------------------------

// AssignTaskResponse

// -------------------------------------------------------------------

// ListTasksRequest

// -------------------------------------------------------------------

// ListTasksResponse

// -------------------------------------------------------------------

// StartTaskRequest

// -------------------------------------------------------------------

// StartTaskResponse

// -------------------------------------------------------------------

// StopTaskRequest

// -------------------------------------------------------------------

// StopTaskResponse

// -------------------------------------------------------------------

// UpdateTaskRequest

// -------------------------------------------------------------------

// UpdateTaskResponse

// -------------------------------------------------------------------

// ExecuteCmdRequest

// -------------------------------------------------------------------

// ExecuteCmdResponse


// @@protoc_insertion_point(namespace_scope)

}  // namespace galaxy
}  // namespace baidu

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_appmaster_2eproto__INCLUDED
